### ISSUE TITLE
HTTP response code not available in callback functions

### ISSUE THREAD

**Issue by kvcrawford** [adrianlee44/ng-backbone#7]
For success and error callbacks, you get the following arguments: `(collection, response, options)`

In the normal Backbone + $.ajax world, [this callback function](https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L863) gets passed to [$.ajax](http://api.jquery.com/jquery.ajax/), where the first argument is `data` (the data response from the server, parsed according to its dataType). Data then gets passed on to be the `response` argument of our callback.

At the same time, the jqXHR object returned by `$.ajax` gets assigned to `options.xhr`, so you are able to look at the response code from there. In contrast with current ng-backbone, `options.xhr` is just the promise returned by $http.

To make things more confusing, `$.ajax`'s error callback gets a `jqXHR` for its first argument...so while backbone's docs say that both callbacks get the same arguments `(collection, response, options)`, response is different for error...and you can grab the HTTP status code from it.

Would you accept a PR that exposes the HTTP status code in some way? What if we did something like this...

```js
var xhr = ajax(_.extend(params, options)).
  success(function(data, status, headers, config) {
    options.xhr = {
      status: status
      headers: headers
      config: config
    }

    if (!isUndefined(options.success) && _.isFunction(options.success)) {
      options.success(data);
    }
  }).
  error(function(data, status, headers, config) {
    options.xhr = {
      status: status
      headers: headers
      config: config
    }

    if (!isUndefined(options.error) && _.isFunction(options.error)) {
      options.error(data);
    }
  });
```

options.xhr still wouldn't be an xhr object ($http doesn't give us that), but it would be a little bit closer. Currently options.xhr is just the same promise that already gets returned by the `fetch`, `create`, etc. functions.

**Comment by adrianlee44** [comment]
Fixed with #8
